#ifndef QO3_KERNEL_APIC_H
#define QO3_KERNEL_APIC_H

#define LOCAL_APIC_BASE		0xfee00000
#define LOCAL_APIC_ID		(LOCAL_APIC_BASE+0x0020)
#define LOCAL_APIC_VERSION	(LOCAL_APIC_BASE+0x0030)
#define LOCAL_APIC_TPR		(LOCAL_APIC_BASE+0x0080)
#define LOCAL_APIC_APR		(LOCAL_APIC_BASE+0x0090)
#define LOCAL_APIC_PPR		(LOCAL_APIC_BASE+0x00A0)
#define LOCAL_APIC_EOI		(LOCAL_APIC_BASE+0x00B0)
#define LOCAL_APIC_EOI		(LOCAL_APIC_BASE+0x00B0)
#define LOCAL_APIC_LOGDEST	(LOCAL_APIC_BASE+0x00D0)
#define LOCAL_APIC_DESTFORMAT	(LOCAL_APIC_BASE+0x00E0)
#define LOCAL_APIC_SVR		(LOCAL_APIC_BASE+0x00F0)

#define LOCAL_APIC_ISR0		(LOCAL_APIC_BASE+0x0100)
#define LOCAL_APIC_ISR1		(LOCAL_APIC_BASE+0x0110)
#define LOCAL_APIC_ISR2		(LOCAL_APIC_BASE+0x0120)
#define LOCAL_APIC_ISR3		(LOCAL_APIC_BASE+0x0130)
#define LOCAL_APIC_ISR4		(LOCAL_APIC_BASE+0x0140)
#define LOCAL_APIC_ISR5		(LOCAL_APIC_BASE+0x0150)
#define LOCAL_APIC_ISR6		(LOCAL_APIC_BASE+0x0160)
#define LOCAL_APIC_ISR7		(LOCAL_APIC_BASE+0x0170)

#define LOCAL_APIC_TMR0		(LOCAL_APIC_BASE+0x0180)
#define LOCAL_APIC_TMR1		(LOCAL_APIC_BASE+0x0190)
#define LOCAL_APIC_TMR2		(LOCAL_APIC_BASE+0x01a0)
#define LOCAL_APIC_TMR3		(LOCAL_APIC_BASE+0x01b0)
#define LOCAL_APIC_TMR4		(LOCAL_APIC_BASE+0x01c0)
#define LOCAL_APIC_TMR5		(LOCAL_APIC_BASE+0x01d0)
#define LOCAL_APIC_TMR6		(LOCAL_APIC_BASE+0x01e0)
#define LOCAL_APIC_TMR7		(LOCAL_APIC_BASE+0x01f0)

#define LOCAL_APIC_IRR0		(LOCAL_APIC_BASE+0x0200)
#define LOCAL_APIC_IRR1		(LOCAL_APIC_BASE+0x0210)
#define LOCAL_APIC_IRR2		(LOCAL_APIC_BASE+0x0220)
#define LOCAL_APIC_IRR3		(LOCAL_APIC_BASE+0x0230)
#define LOCAL_APIC_IRR4		(LOCAL_APIC_BASE+0x0240)
#define LOCAL_APIC_IRR5		(LOCAL_APIC_BASE+0x0250)
#define LOCAL_APIC_IRR6		(LOCAL_APIC_BASE+0x0260)
#define LOCAL_APIC_IRR7		(LOCAL_APIC_BASE+0x0270)

#define LOCAL_APIC_ERROR_STATUS	(LOCAL_APIC_BASE+0x0280)
#define LOCAL_APIC_LVT_CMCI	(LOCAL_APIC_BASE+0x2f0)

#define LOCAL_APIC_ICR0		(LOCAL_APIC_BASE+0x300)
#define LOCAL_APIC_ICR1		(LOCAL_APIC_BASE+0x310)

#define LOCAL_APIC_LVT_TIMER	(LOCAL_APIC_BASE+0x320)
#define LOCAL_APIC_LVT_THERMAL	(LOCAL_APIC_BASE+0x330)
#define LOCAL_APIC_LVT_PMC	(LOCAL_APIC_BASE+0x340)
#define LOCAL_APIC_LVT_LINT0	(LOCAL_APIC_BASE+0x350)
#define LOCAL_APIC_LVT_LINT1	(LOCAL_APIC_BASE+0x360)
#define LOCAL_APIC_LVT_ERROR	(LOCAL_APIC_BASE+0x370)
#define LOCAL_APIC_LVT3		(LOCAL_APIC_LVT_ERROR)
#define LOCAL_APIC_INITIAL_COUNT (LOCAL_APIC_BASE+0x380)
#define LOCAL_APIC_CURRENT_COUNT (LOCAL_APIC_BASE+0x390)
#define LOCAL_APIC_DIVIDE	(LOCAL_APIC_BASE+0x3e0)

#define LOCAL_APIC_SVR_EOI_BROADCAST_DISABLE (1<<11)
#define LOCAL_APIC_SVR_APIC_ENABLE (1<<8)

#define read_local_apic(reg) (*((const unsigned int*)(reg)))
#define write_local_apic(reg, val) ((*((unsigned int*)(reg))) = (val))

#endif
