#ifndef MULTBOOT_H
#define MULTBOOT_H
#define MULTIBOOT_FLAGS_REQUIRE_ALIGN4K (1<<0)
#define MULTIBOOT_FLAGS_REQUIRE_MEMINFO (1<<1)
#define MULTIBOOT_FLAGS_REQUIRE_VIDEOINFO (1<<2)
#define MULTIBOOT_FLAGS_HAS_EXT_HEADER (1<<16)

#endif
