#define PCI_CLS_MULTIMEDIA 4
#define PCI_SUBCLS_HD_AUDIO 3

#define PCI_CLS_BRIDGE 6
#define PCI_SUBCLS_HOST_BRIDGE 0
#define PCI_SUBCLS_PCIPCI_BRIDGE 4

#define PCI_CLS_SERIAL_BUS 0x0c
#define PCI_SUBCLS_USB_HOST_CONTROLLER 0x03

#define PCI_PI_UHCI 0x00
#define PCI_PI_OHCI 0x10
#define PCI_PI_EHCI 0x20
#define PCI_PI_XHCI 0x30

#define PCI_VENDOR_REALTEK 0x10ec
