#ifndef QO3_KERNEL_SEGDESC_H
#define QO3_KERNEL_SEGDESC_H

#define SEGDESC_S	(1<<12)
#define SEGDESC_P	(1<<15)
#define SEGDESC_AVL	(1<<20)
#define SEGDESC_DB	(1<<22)
#define SEGDESC_G	(1<<23)

#define SEGDESC_EXECREAD (0xa<<8)
#define SEGDESC_READWRITE (0x2<<8)

#define SEGDESC_DPL_SHIFT 13
#define SEGDESC_LIMIT_SHIFT 16
#define SEGDESC_BASE_SHIFTL 0
#define SEGDESC_BASE_SHIFTH 24

#endif
