#ifndef NPR_FORMAT_ABBREV_H
#define NPR_FORMAT_ABBREV_H

#ifdef __cplusplus
extern "C" {
#endif

#define DIGIT NPR_FORMAT_DIGIT
#define STR NPR_FORMAT_STR
#define ORDC NPR_FORMAT_ORDINARY_C
#define ORD NPR_FORMAT_ORDINARY
#define CHAR NPR_FORMAT_ORDINARY_CHAR

#define SETARG_INT NPR_PRINTF_SET_ARG_INT
#define SETARG_STRC NPR_PRINTF_SET_ARG_STR_C
#define SETARG_STR NPR_PRINTF_SET_ARG_STR

#ifdef __cplusplus
}
#endif

#endif
